# Squid NodePort Service - Provides stable access to Squid instances on host network
# This service allows direct access to Squid via node IPs for CVMFS and other services
apiVersion: v1
kind: Service
metadata:
  name: squid
  namespace: proxy
  annotations:
    # Rancher management annotations
    field.cattle.io/targetWorkloadIds: '["proxy/squid"]'
    management.cattle.io/ui-managed: 'true'
spec:
  type: NodePort
  ports:
    - name: http-proxy
      port: 3128
      protocol: TCP
      targetPort: 3128
      nodePort: 3128  # Same as container port for simplicity
  selector:
    app: squid
  sessionAffinity: None
