apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2025-08-07T02:06:16Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:clusterIP: {}
          f:internalTrafficPolicy: {}
          f:ipFamilies: {}
          f:ipFamilyPolicy: {}
          f:ports:
            .: {}
            k:{"port":3128,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":3130,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: rancher
      operation: Update
      time: '2025-08-07T02:10:18Z'
  name: squid-peers
  namespace: proxy
  resourceVersion: '65874776'
  uid: 3fe292ea-537e-4372-91a0-0fde0238eb7a
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http-proxy
      port: 3128
      protocol: TCP
      targetPort: 3128
    - name: icp
      port: 3130
      protocol: TCP
      targetPort: 3130
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-proxy-squid
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
