# Squid Cache Configuration - High-performance caching settings for research workloads
# This ConfigMap contains optimized cache settings for CVMFS and research data
apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-config
  namespace: squid-standard
data:
  cache.conf: |
    # ============================================
    # === STORAGE & SIZES ========================
    # ============================================
    
    cache_dir aufs /var/lib/squid 100000 32 512     # 100 GB per node/pod (matches LV size)
    cache_mem 24576 MB                              # 24 GB RAM cache for hot objects and metadata
    maximum_object_size 20480 MB
    maximum_object_size_in_memory 512 KB
    
    
    # ============================================
    # === POLICIES ===============================
    # ============================================
    
    cache_replacement_policy heap LFUDA
    memory_replacement_policy heap GDSF
    
    
    # ============================================
    # === CONCURRENCY / STABILITY ================
    # ============================================
    
    workers 4
    max_filedescriptors 32768
    
    client_persistent_connections on
    server_persistent_connections on
    
    
    # ============================================
    # === DNS ====================================
    # ============================================
    
    dns_nameservers 129.128.5.233 8.8.8.8 1.1.1.1
    
    
    # ============================================
    # === PERFORMANCE FEATURES ==================
    # ============================================
    
    client_db on
    pipeline_prefetch 1
    collapsed_forwarding on                # consolidate identical requests
    read_ahead_gap 16 KB
    quick_abort_min 0 KB
    quick_abort_max 0 KB
    store_dir_select_algorithm least-load   # balances disk I/O across dirs if scaled
    
    
    # ============================================
    # === REFRESH PATTERNS (CVMFS & HPC) ========
    # ============================================
    
    # CVMFS objects: prefer revalidation without refetch
    refresh_pattern -i ^/cvmfs/.*      1440 90% 43200 reload-into-ims ignore-reload
    
    # Common software/data artifacts
    refresh_pattern \.(rpm|deb|tar|gz|bz2|xz|zip|iso|img|whl|egg|dll|so|bin|run)$ 1440 90% 43200 reload-into-ims
    refresh_pattern \.(dat|data|json|xml|yaml|yml)$ 1440 90% 43200 reload-into-ims
    refresh_pattern \.(h5|hdf5|nc|netcdf|fits|fits.gz)$ 1440 90% 43200 reload-into-ims
    refresh_pattern \.(vcf|bam|sam|fastq|fasta)$ 1440 90% 43200 reload-into-ims
    refresh_pattern \.(pdf|doc|docx|ppt|pptx)$ 1440 90% 43200 reload-into-ims
    refresh_pattern \.(jpg|jpeg|png|gif|bmp|tiff|css|js|html|htm)$ 1440 90% 43200 reload-into-ims
    refresh_pattern . 0 20% 4320 reload-into-ims    # default heuristic freshness (up to 3 days)
    
    
    # ============================================
    # === LOGGING (stdout/stderr for K8s) ========
    # ============================================
    
    logformat basic %ts.%03tu %6tr %>a %Ss/%03>Hs %<st %rm %ru %un %Sh/%<a %mt
    access_log stdio:/dev/stdout basic
    cache_log stdio:/dev/stderr
    cache_store_log stdio:/dev/stderr
    
    
    # ============================================
    # === TIMEOUTS (stable but responsive) =======
    # ============================================
    
    connect_timeout 30 seconds
    request_timeout 90 seconds
    read_timeout 15 minutes
    client_lifetime 1 hour
    server_idle_pconn_timeout 120 seconds
    shutdown_lifetime 5 seconds
    
    
    # ============================================
    # === MISC RECOMMENDATIONS ===================
    # ============================================
    
    # Disable ICP and HTCP (not used in this setup)
    icp_port 0
    htcp_port 0
    
    # Coredumps disabled for containers
    coredump_dir /var/lib/squid
    
    # ============================================
    # END OF CONFIG
    # ============================================