# Squid LoadBalancer - MetalLB LoadBalancer for Squid Proxy
# This provides a single entry point while maintaining host networking benefits
apiVersion: v1
kind: Service
metadata:
  name: squid-lb
  namespace: squid-standard
  annotations:
    metallb.universe.tf/allow-shared-ip: squid-lb
    # Rancher management annotations
    field.cattle.io/targetWorkloadIds: '["squid-standard/squid"]'
    management.cattle.io/ui-managed: 'true'
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.40  # Available IP in your subnet
  ports:
    - name: http-proxy
      port: 31234
      protocol: TCP
      targetPort: 31234
  selector:
    app: squid
  sessionAffinity: None
