# Squid Cache Configuration - High-performance caching settings for research workloads
# This ConfigMap contains optimized cache settings for CVMFS and research data
apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-config
  namespace: squid-standard
data:
  cache.conf: |
    # Cache storage configuration for HPC cluster
    cache_dir aufs /var/lib/squid 500000 32 512    # 500GB cache, 32 dirs, 512 subdirs
    
    # Memory cache - 16GB for high performance (adjust based on node memory)
    cache_mem 16384 MB
    
    # Object size limits for large scientific datasets
    maximum_object_size 10240 MB           # 10GB max for large files
    minimum_object_size 0 KB
    
    # Cache replacement policies - LFUDA for research workloads
    cache_replacement_policy heap LFUDA
    memory_replacement_policy heap LFUDA
    
    # Performance tuning for HPC workload
    workers 4                         # Reduced workers for stability (was 16)
    ipcache_size 8192                 # Larger IP cache for many clients
    ipcache_low 85                    # Keep 85% on low memory
    ipcache_high 95                   # Clear at 95%
    
    # DNS configuration for reliable resolution
    dns_nameservers 8.8.8.8 1.1.1.1
    dns_v4_first on
    
    # Advanced features for HPC
    client_db on                      # Track client performance
    pipeline_prefetch 1               # Reduced prefetch for stability (was 2)
    collapsed_forwarding off          # Disabled to prevent large file serialization
    
    # Connection limits for high concurrency
    max_filedescriptors 65536
    client_persistent_connections on
    server_persistent_connections on
    
    # Monitoring and debugging
    debug_options ALL,1
    logformat squid %ts.%03tu %6tr %>a %Ss/%03>Hs %<st %rm %ru %[un %Sh/%<a %mt
    access_log stdio:/dev/stdout squid
    cache_log stdio:/dev/stderr
    cache_store_log stdio:/dev/stderr
    
    # Timeout settings to prevent hangs
    connect_timeout 30 seconds
    request_timeout 60 seconds
    client_lifetime 1 hour
    server_idle_pconn_timeout 60 seconds
    
    # Refresh patterns for HPC and research content (max 1 year = 31536000 seconds)
    refresh_pattern ^/cvmfs/          0       1%      31536000  # 1 year max freshness for CVMFS
    refresh_pattern \.(rpm|deb|tar\.gz|tar\.bz2|zip)$ 0 0% 31536000  # 1 year for packages
    refresh_pattern \.(iso|img)$      0       0%      31536000  # 1 year for disk images
    refresh_pattern \.(dmg|pkg)$      0       0%      31536000  # 1 year for macOS packages
    refresh_pattern \.(exe|msi)$      0       0%      31536000  # 1 year for Windows packages
    refresh_pattern \.(whl|egg)$      0       0%      31536000  # 1 year for Python packages
    refresh_pattern \.(jar|war)$      0       0%      31536000  # 1 year for Java packages
    refresh_pattern \.(dll|so)$       0       0%      31536000  # 1 year for libraries
    refresh_pattern \.(bin|run)$      0       0%      31536000  # 1 year for binaries
    refresh_pattern \.(dat|data)$     0       0%      31536000  # 1 year for data files
    refresh_pattern \.(json|xml|yaml|yml)$ 0 0% 31536000  # 1 year for config files
    refresh_pattern \.(log|txt)$      0       0%      31536000  # 1 year for log files
    refresh_pattern \.(pdf|doc|docx|ppt|pptx)$ 0 0% 31536000  # 1 year for documents
    refresh_pattern \.(mp4|avi|mov|mkv)$ 0 0% 31536000  # 1 year for videos
    refresh_pattern \.(mp3|wav|flac)$ 0 0% 31536000  # 1 year for audio
    refresh_pattern \.(jpg|jpeg|png|gif|bmp|tiff)$ 0 0% 31536000  # 1 year for images
    refresh_pattern \.(css|js|html|htm)$ 0 0% 31536000  # 1 year for web content
    refresh_pattern \.(sql|db|sqlite)$ 0 0% 31536000  # 1 year for databases
    refresh_pattern \.(h5|hdf5|nc|netcdf)$ 0 0% 31536000  # 1 year for scientific data
    refresh_pattern \.(fits|fits.gz)$ 0 0% 31536000  # 1 year for astronomical data
    refresh_pattern \.(vcf|bam|sam|fastq|fasta)$ 0 0% 31536000  # 1 year for genomic data
    refresh_pattern .                 0       5%      604800   # 7 days default for other content