# Squid ClusterIP Service - For internal cluster access only
# With host networking, direct access is via node IPs (e.g., http://node-ip:3128)
apiVersion: v1
kind: Service
metadata:
  name: squid
  namespace: squid-standard
  annotations:
    # Rancher management annotations
    field.cattle.io/targetWorkloadIds: '["squid-standard/squid"]'
    management.cattle.io/ui-managed: 'true'
spec:
  type: ClusterIP
  ports:
    - name: http-proxy
      port: 3128
      protocol: TCP
      targetPort: 3128
  selector:
    app: squid
  sessionAffinity: None
