apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: squid-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.26.92.11-172.26.92.11
  autoAssign: true
  avoidBuggyIPs: false
  serviceAllocationStrategy: "random"
