# Squid Cache Configuration - High-performance caching settings for research workloads
# This ConfigMap contains optimized cache settings for CVMFS and research data
apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-config
  namespace: proxy
data:
  cache.conf: |
    # Cache storage configuration
    cache_dir aufs /cache 100000 16 256
    
    # Memory cache - 32GB for high performance
    cache_mem 32768 MB
    
    # Object size limits
    maximum_object_size 5120 MB
    minimum_object_size 0 KB
    
    # Cache replacement policies - LFUDA for research workloads
    cache_replacement_policy heap LFUDA
    memory_replacement_policy heap LFUDA
    
    # Performance tuning
    workers 8                         # Adjust based on CPU cores
    ipcache_size 4096                 # Larger IP cache
    ipcache_low 90                    # Keep 90% on low memory
    ipcache_high 95                   # Clear at 95%
    
    # Advanced features
    client_db on                      # Track client performance
    pipeline_prefetch 2               # Prefetch pipelined requests
    collapsed_forwarding on           # Collapse identical requests
    
    # Refresh patterns for different content types
    refresh_pattern ^/cvmfs/          0       5%      43200  # 30 days max freshness for CVMFS
    refresh_pattern .                 0       10%     10080  # 7 days default for other content