apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["172.26.92.11"],"port":3128,"protocol":"TCP","serviceName":"proxy:squid-loadbalancer","allNodes":false}]
    field.cattle.io/targetWorkloadIds: '["proxy/squid"]'
    management.cattle.io/ui-managed: 'true'
    metallb.io/ip-allocated-from-pool: squid-pool
    metallb.universe.tf/allow-shared-ip: proxy
  creationTimestamp: '2025-03-26T02:54:51Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"cilium.io/IPAMRequestSatisfied"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
      manager: cilium-operator-lb-ipam
      operation: Update
      subresource: status
      time: '2025-03-26T03:46:10Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:metallb.io/ip-allocated-from-pool: {}
        f:status:
          f:loadBalancer:
            f:ingress: {}
      manager: controller
      operation: Update
      subresource: status
      time: '2025-03-26T03:47:39Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
            f:metallb.universe.tf/allow-shared-ip: {}
        f:spec:
          f:allocateLoadBalancerNodePorts: {}
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:loadBalancerIP: {}
          f:ports:
            .: {}
            k:{"port":3128,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: rancher
      operation: Update
      time: '2025-04-10T04:58:04Z'
  name: squid-loadbalancer
  namespace: proxy
  resourceVersion: '7488275'
  uid: bf60f301-0afb-49ee-b576-454891385b96
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.42.186
  clusterIPs:
    - 10.43.42.186
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 172.26.92.11
  ports:
    - name: squid
      nodePort: 32030
      port: 3128
      protocol: TCP
      targetPort: 3128
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-proxy-squid
  sessionAffinity: None
  type: LoadBalancer
status:
  conditions:
    - lastTransitionTime: '2025-03-26T03:46:10Z'
      message: No pool exists with a CIDR containing '172.26.92.11'
      reason: no_pool
      status: 'False'
      type: cilium.io/IPAMRequestSatisfied
  loadBalancer:
    ingress:
      - ip: 172.26.92.11
        ipMode: VIP
