# Squid Proxy DaemonSet - Deploys one Squid instance per node using host networking
# This provides stable IP addresses for CVMFS and other services that need consistent endpoints
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: squid
  namespace: squid-standard
spec:
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      # Use host networking for stable IP addresses
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      # Ensure pods can bind to host ports
      hostPID: false
      hostIPC: false
      
      containers:
        - name: squid
          image: ubuntu/squid:latest
          imagePullPolicy: Always
          
          # Environment variables for node identification
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          
          
          # Security context - hardened for production
          securityContext:
            allowPrivilegeEscalation: true  # Required for SYS_RESOURCE capability
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 3128  # Squid user ID
            runAsGroup: 3128 # Squid group ID
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE  # Required for binding to privileged ports
                - SYS_RESOURCE      # Required for increasing file descriptor limits
            seccompProfile:
              type: RuntimeDefault
          
          # Resource limits for HPC cluster workload
          resources:
            requests:
              memory: "8Gi"      # 8GB minimum for CVMFS caching
              cpu: "1000m"       # 1 CPU core minimum
              ephemeral-storage: "10Gi"  # Cache storage minimum
            limits:
              memory: "32Gi"     # 32GB maximum (adjust based on node memory)
              cpu: "4000m"       # 4 CPU cores maximum
              ephemeral-storage: "100Gi" # Cache storage maximum
          
          # Volume mounts for configuration and cache
          volumeMounts:
            - mountPath: /etc/squid/whitelist.txt
              name: squid-whitelist
              subPath: whitelist.txt
              readOnly: true
            - mountPath: /etc/squid/conf.d/01-whitelist.conf
              name: squid-whitelist
              subPath: whitelist.conf
              readOnly: true
            - mountPath: /var/lib/squid
              name: cache-dir
            - mountPath: /etc/squid/conf.d/02-cache.conf
              name: cache-config
              subPath: cache.conf
              readOnly: true
            - mountPath: /etc/squid/squid.conf
              name: entrypoint
              subPath: squid.conf
              readOnly: true
            - mountPath: /var/spool/squid
              name: squid-spool
            - mountPath: /tmp
              name: squid-tmp
            - mountPath: /opt/peer-discovery.sh
              name: entrypoint
              subPath: peer-discovery.sh

          # Health checks for better monitoring
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "squid -k check -f /etc/squid/squid.conf"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 3128
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          command:
            - /bin/sh
            - '-c'
            - |
              # Generate static peer configuration before startup
              echo "Initializing peer configuration..."
              /bin/sh /opt/peer-discovery.sh || true
              
              # Start Squid using the entrypoint script (handles logging and cache init)
              exec /usr/local/bin/entrypoint.sh -f /etc/squid/squid.conf -NYC
      
      # Pod configuration
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      
      # Tolerations for host networking and master nodes
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
        - operator: Exists
          effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        - operator: Exists
          effect: NoSchedule
          key: node-role.kubernetes.io/master
        - operator: Exists
          effect: NoSchedule
          key: node.kubernetes.io/unschedulable
      
      # Pod security context
      securityContext:
        fsGroup: 3128
        runAsNonRoot: true
        runAsUser: 3128
        runAsGroup: 3128
        seccompProfile:
          type: RuntimeDefault
      
      # Volumes for configuration and persistent cache
      volumes:
        - name: squid-whitelist
          configMap:
            name: squid-whitelist
            defaultMode: 420
        - name: cache-config
          configMap:
            name: cache-config
            defaultMode: 420
        - name: cache-dir
          hostPath:
            path: /var/lib/squid
            type: DirectoryOrCreate
        - name: entrypoint
          configMap:
            name: entrypoint
            defaultMode: 493
        - name: squid-spool
          hostPath:
            path: /var/lib/squid/spool
            type: DirectoryOrCreate
        - name: squid-tmp
          emptyDir:
            sizeLimit: 1Gi
  
  # Rolling update strategy for zero-downtime updates
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
