# Squid Proxy DaemonSet - Deploys one Squid instance per node using host networking
# This provides stable IP addresses for CVMFS and other services that need consistent endpoints
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: squid
  namespace: proxy
spec:
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      # Use host networking for stable IP addresses
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      
      containers:
        - name: squid
          image: ubuntu/squid:5.2-22.04_beta
          imagePullPolicy: Always
          
          # Environment variables for node identification
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          
          # Ports exposed on host network
          ports:
            - containerPort: 3128
              name: http-proxy
              protocol: TCP
            - containerPort: 3130
              name: icp
              protocol: TCP
          
          # Security context - non-privileged but needs write access for cache
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          
          # Volume mounts for configuration and cache
          volumeMounts:
            - mountPath: /etc/squid/whitelist.txt
              name: squid-whitelist
              subPath: whitelist.txt
            - mountPath: /etc/squid/conf.d/01-whitelist.conf
              name: squid-whitelist
              subPath: whitelist.conf
            - mountPath: /cache
              name: cache-dir
            - mountPath: /etc/squid/conf.d/02-cache.conf
              name: cache-config
              subPath: cache.conf
            - mountPath: /etc/squid/squid.conf
              name: entrypoint
              subPath: squid.conf
      
      # Pod configuration
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      
      # Volumes for configuration and persistent cache
      volumes:
        - name: squid-whitelist
          configMap:
            name: squid-whitelist
            defaultMode: 420
        - name: cache-config
          configMap:
            name: cache-config
            defaultMode: 420
        - name: cache-dir
          hostPath:
            path: /var/lib/squid
            type: DirectoryOrCreate
        - name: entrypoint
          configMap:
            name: entrypoint
            defaultMode: 493
  
  # Rolling update strategy for zero-downtime updates
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1