# Squid Main Configuration - Core Squid proxy settings and access controls
# This ConfigMap contains the main Squid configuration with security ACLs and port settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint
  namespace: squid-standard
data:
  squid.conf: |
    # Network Access Control Lists (ACLs)
    # Define trusted local networks
    acl localnet src 0.0.0.1-0.255.255.255  # RFC 1122 "this" network (LAN)
    acl localnet src 10.0.0.0/8             # RFC 1918 local private network (LAN)
    acl localnet src 100.64.0.0/10          # RFC 6598 shared address space (CGN)
    acl localnet src 169.254.0.0/16         # RFC 3927 link-local (directly plugged) machines
    acl localnet src 172.16.0.0/12          # RFC 1918 local private network (LAN)
    acl localnet src 192.168.0.0/16         # RFC 1918 local private network (LAN)
    acl localnet src fc00::/7               # RFC 4193 local private network range
    acl localnet src fe80::/10              # RFC 4291 link-local (directly plugged) machines
    acl localnet src 127.0.0.0/24           # Localhost range
    
    # Port-based ACLs for security
    acl SSL_ports port 443
    acl Safe_ports port 80          # http
    acl Safe_ports port 21          # ftp
    acl Safe_ports port 443         # https
    acl Safe_ports port 70          # gopher
    acl Safe_ports port 210         # wais
    acl Safe_ports port 1025-65535  # unregistered ports
    acl Safe_ports port 280         # http-mgmt
    acl Safe_ports port 488         # gss-http
    acl Safe_ports port 591         # filemaker
    acl Safe_ports port 777         # multiling http
    
    # Security rules
    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports
    http_access allow localnet manager
    
    # Peer communication for cache clustering
    acl digest_request url_regex ^http://[^/]+/squid-internal-periodic/store_digest$
    http_access allow localnet digest_request
    acl netdb_request url_regex ^http://[^/]+/squid-internal-dynamic/netdb$
    http_access allow localnet netdb_request
    
    # Allow localhost access
    http_access allow localhost
    
    # Include additional configuration files
    include /etc/squid/conf.d/*.conf
    
    # Deny all other access
    http_access deny all
    
    # HTTP proxy port with high concurrency settings
    http_port 3128

    # PID file location
    pid_filename /tmp/squid.pid
  peer-discovery.sh: |
    #!/bin/sh
    set -eu

    OUT_FILE="/etc/squid/conf.d/99-peers.conf"
    MYIP="${MY_POD_IP:-$(hostname -I | tr ' ' '\n' | grep '172.26.92')}"
    HTTP_PORT=3128

    # Static peer list
    PEERS="172.26.92.2 172.26.92.3 172.26.92.4 172.26.92.5 172.26.92.6"

    # Build file, skipping self
    {
      echo "# Peers in the Vulcan cache cluster"
      for ip in $PEERS; do
        [ "$ip" = "$MYIP" ] && continue
        printf 'cache_peer %s sibling %s 0 proxy-only\n' "$ip" "$HTTP_PORT"
      done
    } > "$OUT_FILE"

    echo "Generated peers file:"
    cat "$OUT_FILE"
