# Simple Test Squid - Single pod with host networking
# This is a minimal test to isolate port conflicts
apiVersion: v1
kind: Namespace
metadata:
  name: squid-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-squid
  namespace: squid-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-squid
  template:
    metadata:
      labels:
        app: test-squid
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: squid
          image: ubuntu/squid:latest
          ports:
            - containerPort: 3128
              name: http-proxy
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          resources:
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          command:
            - /bin/sh
            - -c
            - |
              # Create basic Squid config
              cat > /etc/squid/squid.conf << 'EOF'
              http_port 3128
              acl localnet src 0.0.0.1-0.255.255.255
              acl localnet src 10.0.0.0/8
              acl localnet src 172.16.0.0/12
              acl localnet src 192.168.0.0/16
              acl SSL_ports port 443
              acl Safe_ports port 80
              acl Safe_ports port 21
              acl Safe_ports port 443
              acl Safe_ports port 70
              acl Safe_ports port 210
              acl Safe_ports port 1025-65535
              acl Safe_ports port 280
              acl Safe_ports port 488
              acl Safe_ports port 591
              acl Safe_ports port 777
              http_access deny !Safe_ports
              http_access deny CONNECT !SSL_ports
              http_access allow localnet
              http_access allow localhost
              http_access deny all
              coredump_dir /var/spool/squid
              refresh_pattern ^ftp:           1440    20%     10080
              refresh_pattern ^gopher:        1440    0%      1440
              refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
              refresh_pattern .               0       20%     4320
              EOF
              
              # Start Squid
              echo "Starting Squid on port 3128..."
              squid -f /etc/squid/squid.conf -NYC
